accounts/urls.py
from django.urls import path
from . views.auth import CustomAuthToken
from .views import create_user, user_profile, user_login

app_name="accounts"
urlpatterns = [
    path('auth', CustomAuthToken.as_view(), name="auth"),
    path('create_user', create_user.create_user, name="create_user"),
    path('profile', user_profile.profile, name="profile"),
    path('login', user_login.connexion, name="connexion"),
    path('logout', user_login.logoutpage, name="logout"),
]

blog/urls.py
from django.urls import path
from .views import (
    blog_list, blog_create,
    blog_update, blog_item,
    blog_delete
)


app_name='blog'
urlpatterns = [
    path('', blog_list.blog_list, name='blog_list'),
    path('create', blog_create.blog_create, name='blog_create'),
    path('update/<int:id>', blog_update.blog_update, name='blog_update'),
    path('delete/<int:id>', blog_delete.blog_delete, name='blog_delete'),
    path('<int:id>', blog_item.blog_item, name='blog_item'),
]

restframework/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext as _

from .managers import CustomUserManager

from . signals import create_auth_token

class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ('username',)

    objects = CustomUserManager()

    def __str__(self):
        return self.email

blog/models/blog.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    password1 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Saisir un nouveau mot de passe'
        }), label="Mot de passe")
    password2 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirmez votre mot de passe'
        }), label="Répéter votre mot de passe")


    class Meta:
        model = CustomUser
        fields = ('email', 'username')

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control', 'placeholder': 'Saisir votre nom d\'utilisateur ici'
                }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control', 'placeholder': 'Saisir votre adresse-email ici'
                }),
        }

        help_texts = {
            'username': None,
        }



class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username')

accounts/views/create_user.py
from django.shortcuts import render, redirect
from .. forms import CustomUserCreationForm
from django.contrib import messages


def create_user(request):
    if request.method=="POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:profile")
        else:
            messages.error(request, "erreur : les saisis ne sont pas valide. Assurez-vous d'utiliser un mot de passe fort et identique ou essayer avec un autre adresse mail")
    form = CustomUserCreationForm
    context = {'form' : form}
    return render(request, "accounts/create_user.html", context)

accounts/views/user_login.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages



def connexion(request):
    if request.user.is_authenticated:
        return redirect('accounts:profile')
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        print(email, password)
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('accounts:profile')
        else:
            messages.info(request, 'email ou mot de passe est incorrect')
    return render(request, 'accounts/login.html')

def logoutpage(request):
    logout(request)
    return redirect('accounts:connexion')

accounts/views/user_profile.py
from django.shortcuts import render
from rest_framework.authtoken.models import Token
from .. models import CustomUser


def profile(request):
    context = {}
    if request.user.is_authenticated:
        user = CustomUser.objects.get(pk=request.user.id)
        token = Token.objects.get(user=user)
        context['token']=token.key
    return render(request, "accounts/profile.html", context)

blog/views/blog_create.py
from rest_framework.response import Response
from rest_framework.decorators import api_view

from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .. serializers.blog import BlogSerialiser

@api_view(['POST'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def blog_create(request):
    if request.method=='POST':
        serializer =  BlogSerialiser(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)

blog/views/blog_delete.py
from rest_framework.response import Response
from rest_framework.decorators import api_view

from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .. models.blog import Blog
from django.shortcuts import get_object_or_404

@api_view(['GET'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def blog_delete(request, id):
    post = get_object_or_404(Blog, pk=id)
    post.delete()
    return Response({'post' : 'deleted success'})

blog/views/blog_item.py
from rest_framework.response import Response
from rest_framework.decorators import api_view

from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .. serializers.blog import BlogSerialiser
from .. models.blog import Blog
from django.shortcuts import get_object_or_404

@api_view(['GET'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def blog_item(request, id):
    if request.method=='GET':
        post = get_object_or_404(Blog, pk=id)
        serializer = BlogSerialiser(post, many=False)
        return Response(serializer.data)

blog/views/blog_list.py
from rest_framework.response import Response
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from .. serializers.blog import BlogSerialiser
from .. models.blog import Blog

@api_view(['GET'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def blog_list(request):
    if request.method=="GET":
        posts = Blog.objects.all()
        serialiser = BlogSerialiser(posts, many=True)
        return Response(serialiser.data)

blog/views/blog_update.py
from rest_framework.response import Response
from rest_framework.decorators import api_view

from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .. serializers.blog import BlogSerialiser
from .. models.blog import Blog
from django.shortcuts import get_object_or_404

@api_view(['POST'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def blog_update(request, id):
    if request.method=='POST':
        post = get_object_or_404(Blog, pk=id)
        serialiser = BlogSerialiser(post, request.data)
        if serialiser.is_valid():
            serialiser.save()
            return Response(serialiser.data)
        return Response(serialiser.errors)

accounts/templates/accounts/create_user.html
{% extends 'accounts/layout/base.html' %}

{% block title %}<title>Create user</title>{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <h3 class="mt-5">Création d'un compte</h3>
                {% if request.user.is_authenticated %}
                    <p class="text-danger">
                        Vous êtes authentifié en tant <mark>{{ user.username }} - {{ user.email }}</mark>
                        Si vous souhaitez créer un autre compte, veuilez vous <a href="{% url 'accounts:logout' %}">Déconnecter</a>
                    </p>
                {% else %}
                    {% for message in messages %}
                        <p class="text-danger">{{ message }}</p>
                    {% endfor %}
                    <form action="" method="post">{% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-primary" type="submit">Create mon compte</button>
                    </form> 

                    <br /> <br /><hr >
                    <p>
                       avez-vous déjà un compte <a href="{% url 'accounts:connexion' %}">Connectez-vous</a>
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/layout/base.html
<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title>creation user</title>{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/layout/base.html' %}

{% block title %}<title>Connexion</title>{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <h3 class="mt-5">connexion</h3>
                {% for error in messages %}
                    <p class="text-danger">{{ error }}</p>
                {% endfor %}
                <form action="" method="post">{% csrf_token %}
                    <input class="form-control" type="email" name="email" placeholder="adresse mail" required> <br />
                    <input class="form-control" type="password" name="password" placeholder="mot de passe" required> <br />
                    <input type="submit" value="Connexion" class="btn btn-primary">
                </form>
                
                <br /> <br /><hr >
                <p>
                    Vous n'avez pas un compte ? <a href="{% url 'accounts:create_user' %}">Créer un compte</a>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/layout/base.html' %}

{% block title %}<title>Profile</title>{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                {% if request.user.is_authenticated %}
                    <h3 class="mt-5">User Info</h3>
                    <p>Username > {{ request.user.username }}</p>
                    <p>email > {{ request.user.email }}</p>
                    <p>Token > {{ token }}</p>
                    <hr />
                    <p><a href="{% url 'accounts:logout' %}">Déconnexion</a></p>
                {% else %}
                    <h3 class="mt-5">
                        <a href="{% url 'accounts:connexion' %}">Connectez vous</a>
                    </h3>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}